### ISSUE TITLE
Can the comment list show image / audio / video?

### ISSUE THREAD

**Issue by chinalwb** [Asutosh11/CustomerSupportChat#1]
Hi, I like the chat comments list UI. But seems like it can only show text for now.
Can the comment list show image / audio / video? Or do you have any plan for this?

Thanks.

**Comment by Asutosh11** [comment]
Hi. So far it doesn't support image / audio / video. I have planned to add it along with some other features in the next release.

**Comment by chinalwb** [comment]
Thanks. When will be the next release? May I know? BTW I marked "Wathcing" :)

**Comment by bhartimuley** [comment]
How do u handle offline message in this?

**Comment by chinalwb** [comment]
I use sqlite for my project

**Comment by bhartimuley** [comment]
Project not compiling after adding gradle dependency.

On 16-Jun-2017 8:21 AM, "Rain Liu" <notifications@github.com> wrote:

I use sqlite for my project

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Asutosh11/CustomerSupportChat/issues/1#issuecomment-308918965>,
or mute the thread

**Comment by Asutosh11** [comment]
@bhartimuley .. Are you sure you added it properly in build.gradle ? Can I see your build.gradle code ? It works fine when you add in gradle. You might be missing out something.

**Comment by Asutosh11** [comment]
@chinalwb .. Yeah. I get very less free time outside my work. I'm trying to add extra features. Cannot promise a date though. Thanks.
